
[slicer]
	consume_tool_durability = true
	ignore_rotation = false

[basin_cooking]
	enabled = false
	replace_fluid_containers = true

[sprinkler]
	#Range: 10 ~ 2048
	fluid_capacity = 1000
	#Range: 0 ~ 2048
	fluid_per_use = 50

